name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping RTS on Render
        run: curl -s https://rts-xdbm.onrender.com/ > /dev/null
